// Student
export const GET_ALL_PRACTICES_STUDENT = "GET_ALL_PRACTICES_STUDENT";
export const GET_ACTUAL_MODULE = "GET_ACTUAL_MODULE";

export const GET_PRACTICE_ID = "GET_PRACTICE_ID";
export const UPDATE_PRACTICE_STATE = "UPDATE_PRACTICE_STATE";
export const GET_PRACTICE_STATE = "GET_PRACTICE_STATE";

export const LOADING = "LOADING";
export const LOADING_SUCCESS = "LOADING_SUCCESS";
export const LOADING_ERROR = "LOADING_ERROR";

export const RESET_SUCCESS = "RESET_SUCCESS";

// Inspection products
export const LOADING_INSPECTION_PRODUCT = "LOADING_INSPECTION_PRODUCT";
export const CREATE_INSPECTION_PRODUCT_MODULE1 =
  "CREATE_INSPECTION_PRODUCT_MODULE1";

export const CREATE_INSPECTION_PRODUCT_MODULE2 =
  "CREATE_INSPECTION_PRODUCT_MODULE2";

export const CREATE_INSPECTION_PRODUCT_MODULE3 =
  "CREATE_INSPECTION_PRODUCT_MODULE3";

export const CREATE_INSPECTION_PRODUCT_MODULE3_ERROR =
  "CREATE_INSPECTION_PRODUCT_MODULE3_ERROR";

export const RESET_CREATE_PRODUCTS = "RESET_CREATE_PRODUCTS";

export const RESET_ALL_STATE_STUDENT = "RESET_ALL_STATE_STUDENT";

export const GET_ALL_GRAPHICS = "GET_ALL_GRAPHICS";

export const GET_PRODUCTS_INSPECTION_MODULE1 =
  "GET_PRODUCTS_INSPECTION_MODULE1";
export const GET_PRODUCTS_INSPECTION_MODULE2 =
  "GET_PRODUCTS_INSPECTION_MODULE2";
export const GET_PRODUCTS_INSPECTION_MODULE3 =
  "GET_PRODUCTS_INSPECTION_MODULE3";

export const GET_PRODUCTS_FEATURES_MODULE1 = "GET_PRODUCTS_FEATURES_MODULE1";
export const GET_PRODUCTS_FEATURES_MODULE2 = "GET_PRODUCTS_FEATURES_MODULE2";
export const GET_PRODUCTS_FEATURES_MODULE3 = "GET_PRODUCTS_FEATURES_MODULE3";

// subgroup
export const GET_ALL_SUBGROUP = "GET_ALL_SUBGROUP";
export const GET_ACTUAL_SUBGROUP = "GET_ACTUAL_SUBGROUP";
export const CHECK_SUBGROUP = "CHECK_SUBGROUP";
export const CHANGE_GRAPHIC = "CHANGE_GRAPHIC";

// ProgressBar
export const STEP = "STEP";
export const GET_STEPS = "GET_STEPS";
export const RESET_STEPS = "RESET_STEPS";

// Product
export const REVIEW_PRODUCT = "REVIEW_PRODUCT";
export const REJECTED_PRODUCT = "REJECTED_PRODUCT";
export const ACCEPTED_PRODUCT = "ACCEPTED_PRODUCT";
export const REVIEW_PRODUCT_SUBGROUP = "REVIEW_PRODUCT_SUBGROUP";
export const PRODUCT_INDEX = "PRODUCT_INDEX";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const CHANGE_STATE_MESSAGE = "CHANGE_STATE_MESSAGE";
export const RESET_REVIEW_SUBGROUP = "RESET_REVIEW_SUBGROUP";
export const RESET_SELECTED_SUBGROUP = "RESET_SELECTED_SUBGROUP";
export const RESET_PRODUCTS_STATE = "RESET_PRODUCTS_STATE";
export const RESET_ALL_REVIEWS = "RESET_ALL_REVIEWS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

export const GET_CONDITIONS = "GET_CONDITIONS";

// Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const GET_USER = "GET_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGN_OFF = "SIGN_OFF";

// Teacher
export const COURSE_SUCCESS = "COURSE_SUCCESS";
export const COURSE_ERROR = "COURSE_ERROR";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const GET_COURSES = "GET_COURSES";
export const GET_COURSE = "GET_COURSE";
export const GET_ACTUAL_COURSE = "GET_ACTUAL_COURSE";
export const GET_STUDENTS = "GET_STUDENTS";

export const TEACHER_LOADING = "TEACHER_LOADING";
export const TEACHER_LOADING_ERROR = "TEACHER_LOADING_ERROR";

export const DELETE_PRACTICE = "DELETE_PRACTICE";

export const GET_ALL_PRACTICES_SUCCESS = "GET_ALL_PRACTICES_SUCCESS";
export const GET_ALL_PRACTICES_ERROR = "GET_ALL_PRACTICES_ERROR";

export const GET_GROUPS_PRACTICE_1 = "GET_GROUPS_PRACTICE_1";
export const GET_GROUPS_PRACTICE_2 = "GET_GROUPS_PRACTICE_2";
export const GET_GROUPS_PRACTICE_3 = "GET_GROUPS_PRACTICE_3";
